executable = /afs/desy.de/group/flc/pool/silvaand/workarea/ILDConfig/StandardConfig/production/BatchJobs/4f_sw_sl/sw_sl_job.sh
arguments = $(file)
should_transfer_files = False
transfer_executable = False


request_cpus = 2
request_memory = 3000 Mb

log = /nfs/dust/ilc/user/silvaand/sw_sl_analysis/log/$(ClusterId)_$(ProcId).log
output = /nfs/dust/ilc/user/silvaand/sw_sl_analysis/log/$(ClusterId)_$(ProcId).out
error = /nfs/dust/ilc/user/silvaand/sw_sl_analysis/log/$(ClusterId)_$(ProcId).err

queue file from /afs/desy.de/group/flc/pool/silvaand/workarea/ILDConfig/StandardConfig/production/BatchJobs/4f_sw_sl/4f_sw_sl.txt
