executable = /afs/desy.de/group/flc/pool/silvaand/workarea/ILDConfig/StandardConfig/production/BatchJobs/backgrounds/4f/4f_singleZnunu/4f_singleZnunu.sh
arguments = $(file)
should_transfer_files = False
transfer_executable = False


request_cpus = 1
request_memory = 3000 Mb

log = /nfs/dust/ilc/user/silvaand/4f/4f_singleZnunu/log/$(ClusterId)_$(ProcId).log
output = /nfs/dust/ilc/user/silvaand/4f/4f_singleZnunu/log/$(ClusterId)_$(ProcId).out
error = /nfs/dust/ilc/user/silvaand/4f/4f_singleZnunu/log/$(ClusterId)_$(ProcId).err

queue file from /afs/desy.de/group/flc/pool/silvaand/workarea/ILDConfig/StandardConfig/production/BatchJobs/backgrounds/4f/4f_singleZnunu/4f_singleZnunu.txt
