executable = /afs/desy.de/group/flc/pool/silvaand/workarea/ILDConfig/StandardConfig/production/BatchJobs/4f_ww_h/4f_ww_h.sh
arguments = $(file)
should_transfer_files = False
transfer_executable = False


request_cpus = 1
request_memory = 2000 Mb

log = /nfs/dust/ilc/user/silvaand/test/log/$(ClusterId)_$(ProcId).log
output = /nfs/dust/ilc/user/silvaand/test/log/$(ClusterId)_$(ProcId).out
error = /nfs/dust/ilc/user/silvaand/test/log/$(ClusterId)_$(ProcId).err

queue file from /afs/desy.de/group/flc/pool/silvaand/workarea/ILDConfig/StandardConfig/production/BatchJobs/4f_ww_h/4f_ww_h.txt
